Name: Product
Host: 0.0.0.0
Port: 8001


Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3307)/mall?charset=utf8mb4&parseTime=true&loc=Local

CacheRedis:
  - Host: 127.0.0.1:16379
    Type: node # 单节点模式
    Pass:

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400 # 1天


ProductRpc:
  Etcd:
    Hosts:
      - localhost:12379
    Key: product.rpc

Prometheus:
  Host: 0.0.0.0
  Port: 9081
  Path: /metrics

Telemetry:
  Name: product.api
  Endpoint: 127.0.0.1:14268
  Sampler: 1.0
  Batcher: otlphttp