// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc/pay.proto

package pay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付创建
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Oid           int64                  `protobuf:"varint,2,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_rpc_pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pay_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateRequest) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *CreateRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_rpc_pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pay_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 支付详情
type DetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailRequest) Reset() {
	*x = DetailRequest{}
	mi := &file_rpc_pay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailRequest) ProtoMessage() {}

func (x *DetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailRequest.ProtoReflect.Descriptor instead.
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pay_proto_rawDescGZIP(), []int{2}
}

func (x *DetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Oid           int64                  `protobuf:"varint,3,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Source        int64                  `protobuf:"varint,5,opt,name=Source,proto3" json:"Source,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_rpc_pay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pay_proto_rawDescGZIP(), []int{3}
}

func (x *DetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DetailResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DetailResponse) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *DetailResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DetailResponse) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *DetailResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 支付详情
type CallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Oid           int64                  `protobuf:"varint,3,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Source        int64                  `protobuf:"varint,5,opt,name=Source,proto3" json:"Source,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_rpc_pay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pay_proto_rawDescGZIP(), []int{4}
}

func (x *CallbackRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallbackRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CallbackRequest) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *CallbackRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CallbackRequest) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *CallbackRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_rpc_pay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pay_proto_rawDescGZIP(), []int{5}
}

var File_rpc_pay_proto protoreflect.FileDescriptor

const file_rpc_pay_proto_rawDesc = "" +
	"\n" +
	"\rrpc/pay.proto\x12\x03pay\"K\n" +
	"\rCreateRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12\x10\n" +
	"\x03Oid\x18\x02 \x01(\x03R\x03Oid\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x03R\x06Amount\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\rDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8c\x01\n" +
	"\x0eDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03Uid\x18\x02 \x01(\x03R\x03Uid\x12\x10\n" +
	"\x03Oid\x18\x03 \x01(\x03R\x03Oid\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x03R\x06Amount\x12\x16\n" +
	"\x06Source\x18\x05 \x01(\x03R\x06Source\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x03R\x06Status\"\x8d\x01\n" +
	"\x0fCallbackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03Uid\x18\x02 \x01(\x03R\x03Uid\x12\x10\n" +
	"\x03Oid\x18\x03 \x01(\x03R\x03Oid\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x03R\x06Amount\x12\x16\n" +
	"\x06Source\x18\x05 \x01(\x03R\x06Source\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x03R\x06Status\"\x12\n" +
	"\x10CallbackResponse2\xa4\x01\n" +
	"\x03Pay\x121\n" +
	"\x06Create\x12\x12.pay.CreateRequest\x1a\x13.pay.CreateResponse\x121\n" +
	"\x06Detail\x12\x12.pay.DetailRequest\x1a\x13.pay.DetailResponse\x127\n" +
	"\bCallback\x12\x14.pay.CallbackRequest\x1a\x15.pay.CallbackResponseB\aZ\x05./payb\x06proto3"

var (
	file_rpc_pay_proto_rawDescOnce sync.Once
	file_rpc_pay_proto_rawDescData []byte
)

func file_rpc_pay_proto_rawDescGZIP() []byte {
	file_rpc_pay_proto_rawDescOnce.Do(func() {
		file_rpc_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_pay_proto_rawDesc), len(file_rpc_pay_proto_rawDesc)))
	})
	return file_rpc_pay_proto_rawDescData
}

var file_rpc_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_pay_proto_goTypes = []any{
	(*CreateRequest)(nil),    // 0: pay.CreateRequest
	(*CreateResponse)(nil),   // 1: pay.CreateResponse
	(*DetailRequest)(nil),    // 2: pay.DetailRequest
	(*DetailResponse)(nil),   // 3: pay.DetailResponse
	(*CallbackRequest)(nil),  // 4: pay.CallbackRequest
	(*CallbackResponse)(nil), // 5: pay.CallbackResponse
}
var file_rpc_pay_proto_depIdxs = []int32{
	0, // 0: pay.Pay.Create:input_type -> pay.CreateRequest
	2, // 1: pay.Pay.Detail:input_type -> pay.DetailRequest
	4, // 2: pay.Pay.Callback:input_type -> pay.CallbackRequest
	1, // 3: pay.Pay.Create:output_type -> pay.CreateResponse
	3, // 4: pay.Pay.Detail:output_type -> pay.DetailResponse
	5, // 5: pay.Pay.Callback:output_type -> pay.CallbackResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_pay_proto_init() }
func file_rpc_pay_proto_init() {
	if File_rpc_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_pay_proto_rawDesc), len(file_rpc_pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_pay_proto_goTypes,
		DependencyIndexes: file_rpc_pay_proto_depIdxs,
		MessageInfos:      file_rpc_pay_proto_msgTypes,
	}.Build()
	File_rpc_pay_proto = out.File
	file_rpc_pay_proto_goTypes = nil
	file_rpc_pay_proto_depIdxs = nil
}
