// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`   // 手机号
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`  // JWT 令牌
	AccessExpire int64  `json:"accessExpire"` // 令牌过期时间戳
}

type RegisterRequest struct {
	Name     string `json:"name"`     // 用户名
	Gender   int64  `json:"gender"`   // 性别（对应数据库 tinyint）
	Mobile   string `json:"mobile"`   // 手机号
	Password string `json:"password"` // 密码
}

type RegisterResponse struct {
	Id     int64  `json:"id"`     // 用户ID
	Name   string `json:"name"`   // 姓名
	Gender int64  `json:"gender"` // 性别
	Mobile string `json:"mobile"` // 手机号
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}
